[package]
name = "calp"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
encoding_rs = "0.8.35"
itertools = "0.13.0"
regex = "1.11.1"
